[build]
  command = "npm run build"
  publish = ".next"

[[plugins]]
  package = "@netlify/plugin-nextjs"

[build.environment]
  NODE_VERSION = "18.17.0"
  NPM_FLAGS = "--legacy-peer-deps"

# Next.js 페이지 리디렉션
[[redirects]]
  from = "/*"
  to = "/:splat"
  status = 200
  force = false

# API 라우트는 그대로 유지
[[redirects]]
  from = "/api/*"
  to = "/api/:splat"
  status = 200
