[build]
  command = "rm -rf .next && npm run build"
  publish = ".next"

[[plugins]]
  package = "@netlify/plugin-nextjs"

[build.environment]
  NODE_VERSION = "20.18.1"
  NPM_FLAGS = "--legacy-peer-deps"
  NEXT_TELEMETRY_DISABLED = "1"
  # Force cache invalidation
  BUILD_ID = "2025-10-06-v2"

# Next.js 페이지 리디렉션
[[redirects]]
  from = "/*"
  to = "/:splat"
  status = 200
  force = false

# API 라우트는 그대로 유지
[[redirects]]
  from = "/api/*"
  to = "/api/:splat"
  status = 200
